# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ikesu < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tukaelu/ikesu/releases/download/v0.0.1/ikesu_darwin_amd64.zip"
      sha256 "7b89cc970cb70e46dc269f48fe481fc2ba4015d9ebd9d1aa9965f79bc2c213f9"

      def install
        bin.install "ikesu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tukaelu/ikesu/releases/download/v0.0.1/ikesu_darwin_arm64.zip"
      sha256 "89a762927d0c80219e4da9ecc09ab02856f994a02aac3071e1695fdbdf934550"

      def install
        bin.install "ikesu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tukaelu/ikesu/releases/download/v0.0.1/ikesu_linux_arm64.zip"
      sha256 "a75acfdd69a25bebfddb367cffa5cf2638d6c3e31628eb32dd5fc276b2f3a9a4"

      def install
        bin.install "ikesu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tukaelu/ikesu/releases/download/v0.0.1/ikesu_linux_amd64.zip"
      sha256 "c3626f9d4235972298e64b292f7cd92b7f0fcf7f11d3ca35e09594a42fd09dd1"

      def install
        bin.install "ikesu"
      end
    end
  end
end
