# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ikesu < Formula
  desc ""
  homepage ""
  version "0.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tukaelu/ikesu/releases/download/v0.0.6/ikesu_darwin_arm64.zip"
      sha256 "db34ca155995fe096af97b4fe24ccc79df2dd470d4e6d53f3dd1611ba23bd970"

      def install
        bin.install "ikesu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tukaelu/ikesu/releases/download/v0.0.6/ikesu_darwin_amd64.zip"
      sha256 "2854ea34b80ccf1c22ef40627ab3e40eb80c64451e02f8fa2232c1a2d37fd965"

      def install
        bin.install "ikesu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tukaelu/ikesu/releases/download/v0.0.6/ikesu_linux_arm64.zip"
      sha256 "47d61679ada51361747428a6a0b82669e3b7e85a5ccd9bdda44b1a46cd1f38b3"

      def install
        bin.install "ikesu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tukaelu/ikesu/releases/download/v0.0.6/ikesu_linux_amd64.zip"
      sha256 "f806abcdfe46e21c85ff8f156e2855691478135c72a16a3d9e567d599c886114"

      def install
        bin.install "ikesu"
      end
    end
  end
end
