# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sabadashi < Formula
  desc ""
  homepage ""
  version "0.1.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tukaelu/sabadashi/releases/download/v0.1.9/sabadashi_darwin_arm64.zip"
      sha256 "54d9698de948dfba557e3bbbed692fbe693e5973d149c1bdf5f40a2ecec0c976"

      def install
        bin.install "sabadashi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tukaelu/sabadashi/releases/download/v0.1.9/sabadashi_darwin_amd64.zip"
      sha256 "9eb626af3cd1198006b7415e3c8cc6273c78aa5116abe0d377d7f98d93ff7ac9"

      def install
        bin.install "sabadashi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tukaelu/sabadashi/releases/download/v0.1.9/sabadashi_linux_arm64.zip"
      sha256 "0ce350e469a48e06a55cdd815248e8a7aacfb792443e5a593542ca629be3b09b"

      def install
        bin.install "sabadashi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tukaelu/sabadashi/releases/download/v0.1.9/sabadashi_linux_amd64.zip"
      sha256 "a91ba6148dd1ff7f12f85dec6ced3e33ba1629303e4503f5c51da51d821d9b84"

      def install
        bin.install "sabadashi"
      end
    end
  end
end
