# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zgsync < Formula
  desc ""
  homepage ""
  version "0.0.11"

  on_macos do
    on_intel do
      url "https://github.com/tukaelu/zgsync/releases/download/v0.0.11/zgsync_0.0.11_darwin_amd64.zip"
      sha256 "e1b4d368b22e490dd143b9dee98e68ad59415fa8424e18ed8375e03492cf21f4"

      def install
        bin.install "zgsync"
      end
    end
    on_arm do
      url "https://github.com/tukaelu/zgsync/releases/download/v0.0.11/zgsync_0.0.11_darwin_arm64.zip"
      sha256 "974322654a9c96a036bacd82ac38edb49219118f96598f701a7028312387cab8"

      def install
        bin.install "zgsync"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tukaelu/zgsync/releases/download/v0.0.11/zgsync_0.0.11_linux_amd64.tar.gz"
        sha256 "751bdb3485e9b0e41752de8a2e693a32578b209ba771fdd9b136597379f8c668"

        def install
          bin.install "zgsync"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tukaelu/zgsync/releases/download/v0.0.11/zgsync_0.0.11_linux_arm64.tar.gz"
        sha256 "53fb145f2af1fdb04b2169097a6ca6de7fb926bd9d60156bf04686dd8b69625f"

        def install
          bin.install "zgsync"
        end
      end
    end
  end
end
