# This file was generated by GoReleaser. DO NOT EDIT.
cask "zgsync" do
  desc ""
  homepage ""
  version "0.0.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zgsync"

  on_macos do
    on_intel do
      url "https://github.com/tukaelu/zgsync/releases/download/v0.0.16/zgsync_0.0.16_darwin_amd64.zip"
      sha256 "63a99f72bb381ab14e7f5e18a9c16fa627d656ad2508d91e89f18da751457865"
    end
    on_arm do
      url "https://github.com/tukaelu/zgsync/releases/download/v0.0.16/zgsync_0.0.16_darwin_arm64.zip"
      sha256 "7261ac4698589e58eadd5b2d60e50301eadfb732c4e376158a7d191bf91dfc1e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tukaelu/zgsync/releases/download/v0.0.16/zgsync_0.0.16_linux_amd64.tar.gz"
      sha256 "6ec3f75572d7dc79548c6957dd05d41bfdef90c7c42d2e1d79c755ae2608f065"
    end
    on_arm do
      url "https://github.com/tukaelu/zgsync/releases/download/v0.0.16/zgsync_0.0.16_linux_arm64.tar.gz"
      sha256 "655ec0714af2d89d23d4a8c0986d36079a81cabc8bc8c4cb50325763d3e8f46c"
    end
  end

  # No zap stanza required
end
