# This file was generated by GoReleaser. DO NOT EDIT.
cask "zgsync" do
  name "zgsync"
  desc ""
  homepage ""
  version "0.0.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zgsync"

  on_macos do
    on_intel do
      url "https://github.com/tukaelu/zgsync/releases/download/v#{version}/zgsync_#{version}_darwin_amd64.zip"
      sha256 "71f12634875e008fe2053caffd9c6a4e0469ae9f4ea0cef316266f768258dbd6"
    end
    on_arm do
      url "https://github.com/tukaelu/zgsync/releases/download/v#{version}/zgsync_#{version}_darwin_arm64.zip"
      sha256 "89290d456fb5244067d1dfc83216cb65167fa6fddcc57fc654b2754e8e0f5adb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tukaelu/zgsync/releases/download/v#{version}/zgsync_#{version}_linux_amd64.tar.gz"
      sha256 "e0cf651a4dc2032d7f2f0509bcf4dc27767e13218387f0adafb719fdf3bca70f"
    end
    on_arm do
      url "https://github.com/tukaelu/zgsync/releases/download/v#{version}/zgsync_#{version}_linux_arm64.tar.gz"
      sha256 "f1bfa9edd8dff9051eebd3eeff923884350ed89e6975ba13ab3a2392d30b779c"
    end
  end

  # No zap stanza required
end
